
<div class="page-header">
	<h1>
		About phpBeanstalkdAdmin
	</h1>
</div>

<p>
	<a href="http://mnapoli.github.com/phpBeanstalkdAdmin/"><strong>phpBeanstalkdAdmin</strong></a>
	is a Beanstalkd graphical interface for monitoring and administration.
</p>

<p>
	It is based on the <a href="https://github.com/pda/pheanstalk/">Pheanstalk</a> PHP library.
</p>

<p>
	phpBeanstalkdAdmin is developed and maintained by <a href="http://www.mnapoli.fr/">Matthieu Napoli</a>.
</p>
