<div class="page-header">
	<h1>
		phpBeanstalkdAdmin
		<small>The Beanstalkd admin interface</small>
	</h1>
</div>

<form id="parameters" class="well form-inline" action="<?=$this->baseUrl()?>/" method="get">
	<label>
		Server:
		<input id="server" name="server" type="text" value="<?=$this->server?>">
	</label>
	<label class="checkbox">
		<input id="poll" type="checkbox"> refresh every
	</label>
	<label>
		<input id="pollInterval" name="pollInterval" type="number" value="5"> seconds
	</label>
	<button id="parametersApply" type="submit" class="btn btn-primary pull-right">Apply</button>
</form>

<div id="errorMessage" class="alert alert-error hide">
	<a class="close" data-dismiss="alert" href="#">×</a>
	<h4 class="alert-heading">Error!</h4>

	<div class="content"></div>
</div>

<h2>
	Tubes
</h2>

<table id="jobList" class="table table-striped table-bordered">
	<thead>
	<tr>
		<th>Tube</th>
		<th>Next job ID</th>
		<th>Next job Data</th>
		<th>Actions</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td></td>
		<td></td>
		<td><em>refreshing</em></td>
		<td></td>
	</tr>
	</tbody>
</table>

<form id="addJob" class="well form-inline" action="<?=$this->baseUrl()?>/index/add" method="post">

	<h3>Add a job</h3>

	<input id="addJobData" name="data" type="text" placeholder="Data">
	<input id="addJobTube" name="tube" type="text" placeholder="Tube name">
	<button id="addJobSubmit" type="submit" class="btn btn-primary">
		Add to job queue
	</button>

	<div id="addJobSuccess" class="alert alert-success hide">
		<a class="close" data-dismiss="alert" href="#">×</a>
		<strong>Job added to the queue.</strong>
	</div>

</form>

<script>

	function clearTubeList() {
		$("#jobList tbody").empty();
	}

	function addTubeToList(tube, jobId, jobData, jobStatus) {
		$("#jobList tbody").append($(
			'<tr>\
			 	<td><strong>' + tube + '</strong></td>\
				<td>' + jobId + '</td>\
				<td>' + jobData + '</td>\
				<td c$lass="actions">\
					<button class="delete-job btn btn-mini btn-danger" data-job-id="' + jobId + '"\
						onClick="deleteJob(this)">\
						<i class="icon-remove-circle icon-white"></i>\
						Delete the job\
					</button>\
				 </td>\
			 </tr>'
		));
	}

	function refreshList() {
		$("#errorMessage").fadeOut();
		var server = $("#parameters #server").val();
		$.ajax({
			type: "POST",
			url: baseUrl + "/job/get-list",
			dataType: "json",
			data: { server: server },
			success: function(data) {
				clearTubeList();
				for (var i = 0; i < data.length; i++) {
					var line = data[i];
					var tube = line["tube"];
					var jobId = line["id"];
					var jobData = line["data"];
					addTubeToList(tube, jobId, jobData);
				}
			},
			error: function(xhr) {
				$("#jobList tbody").empty();
				$("#errorMessage .content").text(jQuery.parseJSON(xhr.responseText));
				$("#errorMessage").fadeIn();
			}
		});
	}

	function deleteJob(button) {
		var server = $("#parameters #server").val();
		var jobId = $(button).data("job-id");
		$.ajax({
			type: "POST",
			url: baseUrl + "/job/delete",
			dataType: "json",
			data: { server: server, id: jobId },
			success: function(data) {
				refreshList();
			},
			error: function(xhr) {
				messageBox(jQuery.parseJSON(xhr.responseText));
			}
		});
	}

	$(function() {
		refreshList();

		var intervalId;
		$("#parametersApply").click(function(e) {
			e.preventDefault();
			refreshList();
			clearInterval(intervalId);
			var refresh = $("#poll").attr('checked');
			// Auto-refresh
			if (refresh == 'checked') {
				var pollInterval = $("#pollInterval").val();
				if (pollInterval < 0) {
					pollInterval = 1;
				}
				intervalId = setInterval(refreshList, pollInterval * 1000);
			}
		});

		$("#addJobSubmit").click(function(e) {
			e.preventDefault();
			var server = $("#parameters #server").val();
			var data = $("#addJob #addJobData").val();
			var tube = $("#addJob #addJobTube").val();
			$.ajax({
				type: "POST",
				url: baseUrl + "/job/add",
				dataType: "json",
				data: { server: server, data: data, tube: tube },
				success: function(data) {
					$("#addJob #addJobData").val("");
					$("#addJobSuccess").show();
					setTimeout(function() {
						$("#addJobSuccess").fadeOut();
					}, 5000);
					refreshList();
				},
				error: function(xhr) {
					messageBox(jQuery.parseJSON(xhr.responseText));
				}
			});
		});

	});

</script>
