<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>phpBeanstalkdAdmin</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Where are you travelling next?">
	<meta name="author" content="Matthieu Napoli">

	<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/bootstrap-responsive.min.css">

	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/style.css"/>

	<script src="<?=$this->baseUrl()?>/js/jquery-1.7.2.min.js"></script>

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<script>
		var baseUrl = "<?=$this->baseUrl()?>";
	</script>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="https://awespot.fogbugz.com/default.asp?W9">phpBeanstalkdAdmin</a>

			<div class="nav-collapse">
				<ul class="nav">
					<li class="active"><a href="<?=$this->baseUrl()?>/">Home</a></li>
					<li><a href="<?=$this->baseUrl()?>/index/about">About</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class="container">

	<?=$this->layout()->content?>

</div>

<script src="<?=$this->baseUrl()?>/js/bootstrap.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/bootbox.min.js"></script>

<script src="<?=$this->baseUrl()?>/js/messagebox.js"></script>

</body>
</html>